version: '2'

services:
  compiler_default:
    container_name: compiler_default
    build:
      context: .
      dockerfile: ./docker/compiler_default/Dockerfile
  compiler_swift_php:
    container_name: compiler_swift_php
    build:
      context: .
      dockerfile: ./docker/compiler_swift_php/Dockerfile
  compiler_jvm:
    container_name: compiler_jvm
    build:
      context: .
      dockerfile: ./docker/compiler_jvm/Dockerfile
