version: '3'

services:
  # == サービス本体用 ==
  # データベース(PostgreSQL)
  psql:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  # redisサーバ
  redis:
    image: redis:3.2.9-alpine
    volumes:
      - ./data/redis-data:/data
    # ports:
    #   - "6379:6379"

  # 開発環境用
  development:
    tty: true
    build:
      context: .
      dockerfile: ./docker/rails/development/Dockerfile
    env_file: "./.env"
    ports:
      - "3000:3000"
    volumes:
      # - ./data/development-tmp:/app/tmp
      - ./data/development-log:/app/log
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - psql
      - redis
      # - compiler_default
      # - compiler_swift
      # - compiler_jvm_php

  # 本番環境用
  production:
    tty: true
    build:
      context: .
      dockerfile: ./docker/rails/production/Dockerfile
    env_file: "./.env"
    ports:
      - "3000:3000"
    volumes:
      # - ./data/production-tmp:/app/tmp
      - ./data/production-log:/app/log
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - psql
      - redis
      # - compiler_default
      # - compiler_swift
      # - compiler_jvm_php

  # == コンパイラモジュール用 ==
  compiler_default:
    container_name: compiler_default
    build:
      context: .
      dockerfile: ./docker/compiler_default/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  compiler_swift:
    container_name: compiler_swift
    build:
      context: .
      dockerfile: ./docker/compiler_swift/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  compiler_jvm_php:
    container_name: compiler_jvm_php
    build:
      context: .
      dockerfile: ./docker/compiler_jvm_php/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
