version: '2'

services:
  # == サービス本体用 ==
  # データベース(PostgreSQL)
  psql:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  # redisサーバ
  redis:
    image: redis:3.2.9-alpine
    volumes:
      - ./data/redis-data:/data

  # Nginx(本番環境用)
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/production-tmp:/app/tmp
      - ./data/production-public:/app/public
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    # links:
    #   - production
    depends_on:
      - production

  # 開発環境用
  development:
    tty: true
    build:
      context: .
      dockerfile: ./docker/rails/development/Dockerfile
    env_file: "./.env"
    ports:
      - "3000:3000"
    volumes:
      - ./data/development-tmp:/app/tmp
      - ./data/development-log:/app/log
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - psql
      - redis

  # 本番環境用
  production:
    tty: true
    build:
      context: .
      dockerfile: ./docker/rails/production/Dockerfile
    env_file: "./.env"
    # ports:
    #   - "3000:3000"
    volumes:
      - ./data/production-tmp:/app/tmp
      - ./data/production-public:/app/public
      - ./data/production-log:/app/log
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - psql
      - redis

  # == コンパイラモジュール用 ==
  compiler_default:
    container_name: compiler_default
    build:
      context: .
      dockerfile: ./docker/compiler_default/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  compiler_swift:
    container_name: compiler_swift
    build:
      context: .
      dockerfile: ./docker/compiler_swift/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  compiler_jvm_php:
    container_name: compiler_jvm_php
    build:
      context: .
      dockerfile: ./docker/compiler_jvm_php/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
